version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cinema_db
    restart: always
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"